import math
import time

max_primes : int = 0
best_pair : tuple = (0, 0)

# not solved by myself
# first iterate over all primes below 1000
# iterate over every odd number between -1000 and 1000
# set n zero for every iteration, n is the prime counter
# in a while loop check if numbers generated by n * n + a * n + b are prime
# if they are prime, increment n
# compare if the current n is higher then the highest, of so update it
# store the values of a and b in a tuple to print the solution

def is_prime(num: int) -> bool:
    if num <= 1:
        return False
    for i in range(2, math.isqrt(num) + 1):
        if num % i == 0:
            return False
    return True

if __name__ == '__main__':
    start_time = time.time()

    for b in range(0, 1000):
        if not is_prime(b):
            continue
        for a in range(-999, 1000, 2):
            n = 0
            while is_prime(n * n + a * n + b):
                n += 1
            if n > max_primes:
                max_primes = n
                best_pair = (a, b)
                print(max_primes, best_pair)

    end_time = time.time()

    print("The product of the coefficients %d and %d is %d and produces %d primes" % (best_pair[0], best_pair[1], best_pair[0] * best_pair[1], max_primes))
    print("The calculation took %f seconds." % (end_time - start_time))
